### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jalovisko** [jdlubrano/cad_volume#1]
This looks great! But I wonder what is the license of this repository? MIT, GPL, or something else?

**Comment by jdlubrano** [comment]
Hello @jalovisko 👋 .  I went ahead and added an MIT license to this repo.  Hopefully that suits your use case.  In general, however, I haven't looked at this repo in a long, long time, and I am no longer working in the CAD space.  I am not entirely certain whether this code continues to function.  If you want to borrow a snippet or use this codebase, please feel free to do so, but I am not planning to provide any support for it if something is broken or has become broken.
